# Generated by Django 5.1.6 on 2025-03-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_app', '0003_user_profile_photo_alter_role_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
