# Generated by Django 5.1.6 on 2025-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_app', '0004_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтвержден'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
